### PR TITLE
0.1.4

### PR DESCRIPTION
**Pull request by nwtn**
@celsodantas @tmlayton  @Shopify/tnt

i had already updated the version in `lib/twine-rails/version.rb` but forgot to do so in `package.json` and `bower.json`. this does that, along with a `bundle install` and `make .all && make .uglify`.

### CODE REVIEW

**Comment by tmlayton** [comment]
Seems reasonable, I haven't done a release of Twine though

**Comment by celsodantas** [comment]
For reference https://github.com/Shopify/twine/pull/25/files

**Comment by celsodantas** [comment]
:+1:

**Comment by qq99** [comment]
:+1:

**Pull request merged**
