### PR TITLE
Add mouseenter mouseleave

### PR DESCRIPTION
**Pull request by tmlayton**
Review @qq99 @pushrax

### CODE REVIEW

**Comment by qq99** [comment]
:+1:

**Comment by pushrax** [comment]
:+1: assuming we actually need these events for something that mouseover/mouseout will not work for.

**Comment by qq99** [comment]
I was curious what the difference was, researched to find this:

>the mouseover and mouseout events fire for a given element if the user mouses over or out of an element nested within the given element

So it seems like `mouseenter` and `mouseleave` don't fire if you mouse into a child~

:+1: sounds like a legit addition

**Comment by tmlayton** [comment]
It's legit, although I could remove mouseover and mouseout as they were being added for what I will now being using mouseenter and mouseleave for

**Comment by tmlayton** [comment]
`mouseover` and `mouseout` are a bit like spray and pray

**Comment by qq99** [comment]
I'd leave `mosueover` and `mouseout` in

**Comment by tmlayton** [comment]
Will do, okay to merge?

**Comment by qq99** [comment]
:ship:

**Pull request merged**
