### PR TITLE
Remove jQuery.toggleClass

### PR DESCRIPTION
**Pull request by asmockler**
Addresses #50. Should be noted that `classList.toggle` still doesn't work on SVGs in IE11. Everything else should be good according to [caniuse](http://caniuse.com/#search=classlist).

Very small change but thought I would go ahead and do it.

cc @Shopify/tnt

### CODE REVIEW

**Comment by pushrax** [comment]
The previous code would add the class if the value is truthy and remove the class if falsy. The new code does something different.

**Comment by pushrax** [comment]
A test should really be failing here :s

**Comment by TheMallen** [comment]
`node.classList.toggle` also takes a second parameter similar to jquery's, we should just use that.

**Comment by asmockler** [comment]
IE11 [doesn't support](http://caniuse.com/#search=classlist) the second parameter for `node.classList.toggle` so we will just have to wrap it in an `if` statement. Planning on doing it soon - just keep getting distracted.

**Pull request closed without merging**
