### PR TITLE
Guard against null while getting context

### PR DESCRIPTION
**Pull request by qq99**
cc @patrickdonovan 
Fairly self-explanatory, the line above can set `node` to `null` and we don't protect against this, causing the method to throw

### CODE REVIEW

**Comment by pushrax** [comment]
Can this be merged?

**Comment by qq99** [comment]
:ship:? cc @Shopify/tnt

**Comment by DrewMartin** [comment]
:+1:

**Comment by maartenvg** [comment]
Is the version number change till cool? If so: :+1:

**Comment by qq99** [comment]
yeah, I had to re-write the version bump

**Pull request merged**
